import type { ItemData } from './ItemConfig';

export const ITEMS: Record<string, ItemData> = {
    // ==========================================
    // SILVER ITEMS (Stat Boosts) — Organized by Category & Tier
    // ==========================================

    // --- ATTACK BOOST (3 tiers) ---
    'iron_weight': {
        id: 'iron_weight',
        name: 'Iron Weight',
        description: 'Increases Attack Damage by 10%',
        type: 'SILVER',
        rarity: 'COMMON',
        effects: [{ targetStat: 'attackDamage', value: 0.10, operation: 'ADD' }],
        iconColor: 0xaaaaaa,
        tags: ['attack', 'weapon'],
    },
    'battle_gauntlet': {
        id: 'battle_gauntlet',
        name: 'Battle Gauntlet',
        description: 'Increases Attack Damage by 25%',
        type: 'SILVER',
        rarity: 'UNCOMMON',
        effects: [{ targetStat: 'attackDamage', value: 0.25, operation: 'ADD' }],
        iconColor: 0xcc6600,
        tags: ['attack', 'weapon'],
    },
    'berserker_mark': {
        id: 'berserker_mark',
        name: "Berserker's Mark",
        description: 'Increases Attack Damage by 50%',
        type: 'SILVER',
        rarity: 'RARE',
        effects: [{ targetStat: 'attackDamage', value: 0.50, operation: 'ADD' }],
        iconColor: 0xff2200,
        tags: ['attack', 'damage', 'fire'],
    },

    // --- DEFENSE ARMOR (3 tiers) — NEW MECHANIC ---
    'wooden_shield': {
        id: 'wooden_shield',
        name: 'Wooden Shield',
        description: 'Absorbs 1 hit before breaking',
        type: 'SILVER',
        rarity: 'COMMON',
        effects: [{ targetStat: 'armor', value: 1, operation: 'ADD' }],
        armorHits: 1,
        iconColor: 0x885522,
        tags: ['defense', 'shield'],
    },
    'iron_shield': {
        id: 'iron_shield',
        name: 'Iron Shield',
        description: 'Absorbs 2 hits before breaking',
        type: 'SILVER',
        rarity: 'UNCOMMON',
        effects: [{ targetStat: 'armor', value: 2, operation: 'ADD' }],
        armorHits: 2,
        iconColor: 0x888888,
        tags: ['defense', 'shield', 'armor'],
    },
    'diamond_shield': {
        id: 'diamond_shield',
        name: 'Diamond Shield',
        description: 'Absorbs 3 hits before breaking',
        type: 'SILVER',
        rarity: 'RARE',
        effects: [{ targetStat: 'armor', value: 3, operation: 'ADD' }],
        armorHits: 3,
        iconColor: 0x44ddff,
        tags: ['defense', 'shield', 'armor'],
    },

    // --- MOVEMENT SPEED (3 tiers) ---
    'winged_boots': {
        id: 'winged_boots',
        name: 'Winged Boots',
        description: 'Increases Move Speed and Attack Speed by 15%',
        type: 'SILVER',
        rarity: 'COMMON',
        effects: [
            { targetStat: 'moveSpeed', value: 0.15, operation: 'ADD' },
            { targetStat: 'attackSpeed', value: -0.15, operation: 'ADD' }
        ],
        iconColor: 0x00ffff,
        tags: ['speed', 'mobility'],
    },
    'mercury_sandals': {
        id: 'mercury_sandals',
        name: 'Mercury Sandals',
        description: 'Increases Move Speed and Attack Speed by 30%',
        type: 'SILVER',
        rarity: 'UNCOMMON',
        effects: [
            { targetStat: 'moveSpeed', value: 0.30, operation: 'ADD' },
            { targetStat: 'attackSpeed', value: -0.30, operation: 'ADD' }
        ],
        iconColor: 0x00ddff,
        tags: ['speed', 'mobility'],
    },
    'tempest_boots': {
        id: 'tempest_boots',
        name: 'Tempest Boots',
        description: 'Increases Move Speed and Attack Speed by 50%',
        type: 'SILVER',
        rarity: 'RARE',
        effects: [
            { targetStat: 'moveSpeed', value: 0.50, operation: 'ADD' },
            { targetStat: 'attackSpeed', value: -0.50, operation: 'ADD' }
        ],
        iconColor: 0x0088ff,
        tags: ['speed', 'mobility'],
    },

    // --- HEALTH UPGRADE (3 tiers) ---
    'heart_shard': {
        id: 'heart_shard',
        name: 'Heart Shard',
        description: 'Increases Max Health by 1',
        type: 'SILVER',
        rarity: 'COMMON',
        effects: [{ targetStat: 'health', value: 1, operation: 'ADD' }],
        iconColor: 0xff4444,
        tags: ['health', 'heal', 'defense'],
    },
    'heart_container': {
        id: 'heart_container',
        name: 'Heart Container',
        description: 'Increases Max Health by 2',
        type: 'SILVER',
        rarity: 'UNCOMMON',
        effects: [{ targetStat: 'health', value: 2, operation: 'ADD' }],
        iconColor: 0xff0000,
        tags: ['health', 'heal'],
    },
    'heart_crystal': {
        id: 'heart_crystal',
        name: 'Heart Crystal',
        description: 'Increases Max Health by 3',
        type: 'SILVER',
        rarity: 'RARE',
        effects: [{ targetStat: 'health', value: 3, operation: 'ADD' }],
        iconColor: 0xff0000,
        tags: ['health', 'heal'],
    },

    // --- JUMP HEIGHT (3 tiers) ---
    'feather_anklet': {
        id: 'feather_anklet',
        name: 'Feather Anklet',
        description: 'Increases Jump Height by 10%',
        type: 'SILVER',
        rarity: 'COMMON',
        effects: [{ targetStat: 'jumpHeight', value: 0.10, operation: 'ADD' }],
        iconColor: 0xcccc00,
        tags: ['jump', 'mobility'],
    },
    'moon_stone': {
        id: 'moon_stone',
        name: 'Moon Stone',
        description: 'Increases Jump Height by 15%',
        type: 'SILVER',
        rarity: 'UNCOMMON',
        effects: [{ targetStat: 'jumpHeight', value: 0.15, operation: 'ADD' }],
        iconColor: 0xaaaa00,
        tags: ['jump', 'mobility'],
    },
    'sky_crystal': {
        id: 'sky_crystal',
        name: 'Sky Crystal',
        description: 'Increases Jump Height by 25%',
        type: 'SILVER',
        rarity: 'RARE',
        effects: [{ targetStat: 'jumpHeight', value: 0.25, operation: 'ADD' }],
        iconColor: 0xffff00,
        tags: ['jump', 'mobility'],
    },

    // --- ATTACK SPEED (2 tiers) ---
    'swift_blade': {
        id: 'swift_blade',
        name: 'Swift Blade',
        description: 'Increases Attack Speed by 15%',
        type: 'SILVER',
        rarity: 'COMMON',
        effects: [{ targetStat: 'attackSpeed', value: -0.15, operation: 'ADD' }], // Lower is faster
        iconColor: 0x0000ff,
        tags: ['attack', 'weapon'],
    },
    'chronos_edge': {
        id: 'chronos_edge',
        name: "Chrono's Edge",
        description: 'Increases Attack Speed by 30%',
        type: 'SILVER',
        rarity: 'RARE',
        effects: [{ targetStat: 'attackSpeed', value: -0.30, operation: 'ADD' }],
        iconColor: 0x2244ff,
        tags: ['attack', 'weapon', 'cooldown'],
    },

    // GOLD ITEMS (Abilities)
    'hermes_feather': {
        id: 'hermes_feather',
        name: 'Hermes Feather',
        description: 'Grants Double Jump',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'double_jump',
        iconColor: 0xffd700,
        stackable: true,
        stackDescription: 'Triple Jump instead of Double Jump',
        tags: ['jump', 'mobility'],
    },
    'vampiric_fang': {
        id: 'vampiric_fang',
        name: 'Vampiric Fang',
        description: 'Heal 1 HP on every 10th kill',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'vampirism',
        iconColor: 0xff0044,
        tags: ['heal', 'regen', 'attack'],
    },
    'phoenix_plume': {
        id: 'phoenix_plume',
        name: 'Phoenix Plume',
        description: 'Revive once per run with 1 HP',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'revive',
        iconColor: 0xff6600,
        tags: ['heal', 'fire', 'defense'],
    },
    'shadow_cloak': {
        id: 'shadow_cloak',
        name: 'Shadow Cloak',
        description: 'Dodge grants brief invisibility',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'shadow_dodge',
        iconColor: 0x440066,
        tags: ['dodge', 'stealth', 'evasion'],
    },
    'titans_grip': {
        id: 'titans_grip',
        name: "Titan's Grip",
        description: 'Attacks have +50% knockback',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'mega_knockback',
        iconColor: 0x884400,
        tags: ['attack', 'weapon', 'damage'],
    },
    'essence_magnet': {
        id: 'essence_magnet',
        name: 'Essence Magnet',
        description: '+25% essence from all sources',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'essence_boost',
        iconColor: 0xcc44ff,
        tags: ['essence', 'gold', 'luck'],
    },
    'wind_runner': {
        id: 'wind_runner',
        name: 'Wind Runner',
        description: 'Press Shift in midair to air dash',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'air_dash',
        iconColor: 0x88ccff,
        stackable: true,
        stackDescription: 'Air Dash cooldown reduced to 0.8s',
        tags: ['speed', 'mobility'],
    },
    'spider_silk': {
        id: 'spider_silk',
        name: 'Spider Silk',
        description: 'Hold toward wall to climb upward',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'wall_climb',
        iconColor: 0xcccccc,
        tags: ['mobility', 'stealth'],
    },
    'chain_hook': {
        id: 'chain_hook',
        name: 'Chain Hook',
        description: 'Press V to grapple to nearest platform',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'grappling_hook',
        iconColor: 0x886644,
        tags: ['mobility', 'weapon'],
    },
    'life_spring': {
        id: 'life_spring',
        name: 'Life Spring',
        description: 'Regenerate 1 HP every 30 seconds out of combat',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'health_regen',
        iconColor: 0x44ff44,
        stackable: true,
        stackDescription: 'Regen timer reduced to 20s',
        tags: ['heal', 'regen', 'health'],
    },
    'phantom_step': {
        id: 'phantom_step',
        name: 'Phantom Step',
        description: 'Double i-frames and halved dodge cooldown',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'dodge_mastery',
        iconColor: 0x8844ff,
        stackable: true,
        stackDescription: 'Adds damaging afterimage trail on dodge',
        tags: ['dodge', 'evasion', 'speed'],
    },
    'mirror_shield': {
        id: 'mirror_shield',
        name: 'Mirror Shield',
        description: 'Reflect 30% of damage back to attackers',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'damage_reflect',
        iconColor: 0x44ddff,
        stackable: true,
        stackDescription: '60% damage reflection instead of 30%',
        tags: ['defense', 'shield', 'damage'],
    },
    'guardian_angel': {
        id: 'guardian_angel',
        name: 'Guardian Angel',
        description: '3s invincibility when health drops to 1 (once per run)',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'temp_shield',
        iconColor: 0xffdd44,
        stackable: true,
        stackDescription: 'Second activation after 5 minutes',
        tags: ['defense', 'heal'],
    },
    'cataclysm_orb': {
        id: 'cataclysm_orb',
        name: 'Cataclysm Orb',
        description: 'Press Q for massive explosion (500% damage, 60s cooldown)',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'cataclysm',
        iconColor: 0xff2200,
        tags: ['fire', 'damage', 'ability', 'ultimate'],
    },
    'chrono_shard': {
        id: 'chrono_shard',
        name: 'Chrono Shard',
        description: 'Press E to slow time to 30% for 5 seconds (90s cooldown)',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'temporal_rift',
        iconColor: 0x22aaff,
        stackable: true,
        stackDescription: 'Time slow lasts 8s instead of 5s',
        tags: ['cooldown', 'ability', 'ultimate'],
    },
    'divine_halo': {
        id: 'divine_halo',
        name: 'Divine Halo',
        description: 'Press R for 5 seconds of invincibility (120s cooldown)',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'divine_intervention',
        iconColor: 0xffffaa,
        tags: ['defense', 'ability', 'ultimate'],
    },
    'essence_crystal': {
        id: 'essence_crystal',
        name: 'Essence Crystal',
        description: 'Press F to convert essence into temporary power (+10% stats per 100 essence, 30s)',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'essence_burst',
        iconColor: 0xcc44ff,
        tags: ['essence', 'ability', 'gold'],
    },
    'counter_slash': {
        id: 'counter_slash',
        name: 'Counter Slash',
        description: 'Press G to enter counter stance (0.5s). If hit: negate damage and counter-attack',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'counter_stance',
        iconColor: 0xff8844,
        tags: ['attack', 'dodge', 'evasion'],
    },
    'ground_slam': {
        id: 'ground_slam',
        name: 'Ground Slam',
        description: 'Press T to slam the ground, creating a damaging shockwave',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'ground_slam',
        iconColor: 0x886633,
        tags: ['attack', 'damage', 'fire'],
    },
    'projectile_shot': {
        id: 'projectile_shot',
        name: 'Arcane Bolt',
        description: 'Press Y to fire a piercing projectile',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'projectile_shot',
        iconColor: 0x44aaff,
        tags: ['attack', 'ability', 'cooldown'],
    },
    'charged_devastation': {
        id: 'charged_devastation',
        name: 'Charged Devastation',
        description: 'Hold H to charge, release for up to 3x damage',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'charged_attack',
        iconColor: 0xff4400,
        tags: ['attack', 'damage', 'fire'],
    },

    // --- Missing Design-Doc Gold Items ---

    // Movement
    'speed_demon': {
        id: 'speed_demon',
        name: 'Speed Demon',
        description: 'Permanently increases Move Speed by 30%',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'speed_demon',
        iconColor: 0x00ff88,
        stackable: true,
        stackDescription: '+60% Move Speed instead of 30%',
        tags: ['speed', 'mobility'],
    },

    // Combat
    'critical_eye': {
        id: 'critical_eye',
        name: 'Critical Eye',
        description: '20% chance for attacks to deal 2x damage',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'critical_strike',
        iconColor: 0xff2222,
        stackable: true,
        stackDescription: '35% crit chance instead of 20%',
        tags: ['attack', 'crit', 'damage'],
    },
    'phantom_blade': {
        id: 'phantom_blade',
        name: 'Phantom Blade',
        description: 'Attacks pierce through enemies, hitting all in range',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'piercing_attacks',
        iconColor: 0xaa66ff,
        stackable: true,
        stackDescription: 'Piercing attacks also deal +25% damage',
        tags: ['attack', 'weapon'],
    },
    'berserker_heart': {
        id: 'berserker_heart',
        name: "Berserker's Heart",
        description: 'Deal +50% damage when at 1 HP',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'berserker_rage',
        iconColor: 0xcc0000,
        stackable: true,
        stackDescription: '+100% damage at 1 HP instead of 50%',
        tags: ['attack', 'damage', 'fire'],
    },

    // Defense
    'second_wind': {
        id: 'second_wind',
        name: 'Second Wind',
        description: 'Heal to full HP once when dropping below 1 HP',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'second_wind',
        iconColor: 0x44ff88,
        stackable: true,
        stackDescription: 'Second Wind can trigger twice per run',
        tags: ['heal', 'regen', 'defense'],
    },
    'thorns_aura': {
        id: 'thorns_aura',
        name: 'Thorns Aura',
        description: 'Enemies within melee range take 1 damage per second',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'thorns_aura',
        iconColor: 0x44aa44,
        stackable: true,
        stackDescription: '2 damage per second instead of 1',
        tags: ['damage', 'fire', 'defense'],
    },
    'absorption_shield': {
        id: 'absorption_shield',
        name: 'Absorption Shield',
        description: 'Generate a shield that absorbs 1 hit every 30 seconds',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'absorption_shield',
        iconColor: 0x4488cc,
        stackable: true,
        stackDescription: 'Shield recharges every 20 seconds instead of 30',
        tags: ['defense', 'shield', 'armor'],
    },

    // Utility
    'magnet_ring': {
        id: 'magnet_ring',
        name: 'Magnet Ring',
        description: 'Items are pulled toward you from a greater distance',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'magnet_pull',
        iconColor: 0xff4488,
        stackable: true,
        stackDescription: 'Even larger pull range',
        tags: ['luck', 'essence'],
    },
    'lucky_dice': {
        id: 'lucky_dice',
        name: 'Lucky Dice',
        description: 'Silver items are more likely to be Pristine quality',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'lucky_dice',
        iconColor: 0x44ff44,
        stackable: true,
        stackDescription: 'Silver items are always Pristine',
        tags: ['luck', 'gold'],
    },
    'scout_lens': {
        id: 'scout_lens',
        name: 'Scout Lens',
        description: 'Shows an indicator when items are nearby off-screen',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'item_radar',
        iconColor: 0xffaa00,
        tags: ['luck', 'stealth'],
    },
    'soul_collector': {
        id: 'soul_collector',
        name: 'Soul Collector',
        description: '+15% bonus essence from all kills',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'soul_collector',
        iconColor: 0x8844cc,
        stackable: true,
        stackDescription: '+30% bonus essence instead of 15%',
        tags: ['essence', 'gold', 'luck'],
    },

    // --- CLASS-SPECIFIC GOLD ITEMS (Boss 10 Reward) ---
    'divine_aegis': {
        id: 'divine_aegis',
        name: 'Divine Aegis',
        description: 'Paladin Exclusive: Blocking reflects 100% damage and heals 1 HP on perfect parry',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'divine_aegis',
        iconColor: 0x3355ff,
        stackable: false,
        tags: ['defense', 'shield'],
    },
    'eternal_flow': {
        id: 'eternal_flow',
        name: 'Eternal Flow',
        description: 'Monk Exclusive: Flow meter never decays and grants 20% move speed at max flow',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'eternal_flow',
        iconColor: 0xffaa00,
        stackable: false,
        tags: ['speed', 'ability'],
    },
    'sacred_relic': {
        id: 'sacred_relic',
        name: 'Sacred Relic',
        description: 'Priest Exclusive: Sacred Ground heals +1 HP and cooldown reduced by 50%',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'sacred_relic',
        iconColor: 0xffffff,
        stackable: false,
        tags: ['heal', 'cooldown', 'ability'],
    },

    // ==========================================
    // CURSED ITEMS — Powerful benefits with significant downsides
    // ==========================================

    'blood_blade': {
        id: 'blood_blade',
        name: 'Blood Blade',
        description: '+75% Attack Damage. CURSE: Lose 1 HP every 10 kills.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'blood_blade',
        abilityId: 'curse_blood_blade',
        effects: [{ targetStat: 'attackDamage', value: 0.75, operation: 'ADD' }],
        iconColor: 0x9933cc,
        tags: ['attack', 'damage'],
    },
    'glass_cannon': {
        id: 'glass_cannon',
        name: 'Glass Cannon',
        description: '+100% Attack Damage. CURSE: Max HP capped at 3.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'glass_cannon',
        abilityId: 'curse_glass_cannon',
        effects: [{ targetStat: 'attackDamage', value: 1.00, operation: 'ADD' }],
        iconColor: 0x9933cc,
        tags: ['attack', 'damage'],
    },
    'temporal_drain': {
        id: 'temporal_drain',
        name: 'Temporal Drain',
        description: 'Cooldowns reduced 50%. CURSE: Move 20% slower.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'temporal_drain',
        abilityId: 'curse_temporal_drain',
        effects: [{ targetStat: 'moveSpeed', value: -0.20, operation: 'ADD' }],
        iconColor: 0x9933cc,
        tags: ['cooldown', 'ability'],
    },
    'chaos_orb': {
        id: 'chaos_orb',
        name: 'Chaos Orb',
        description: 'Random bonus on each attack. CURSE: Take 1 damage every 60 seconds.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'chaos_orb',
        abilityId: 'curse_chaos_orb',
        iconColor: 0x9933cc,
        tags: ['attack', 'fire'],
    },
    'soul_siphon': {
        id: 'soul_siphon',
        name: 'Soul Siphon',
        description: 'Kills heal 1 HP. CURSE: Essence gain reduced 50%.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'soul_siphon',
        abilityId: 'curse_soul_siphon',
        iconColor: 0x9933cc,
        tags: ['heal', 'essence'],
    },
    'cursed_phantom_step': {
        id: 'cursed_phantom_step',
        name: 'Phantom Step',
        description: 'Grants Triple Jump. CURSE: Wall-jump disabled.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'phantom_step',
        abilityId: 'curse_phantom_step',
        iconColor: 0x9933cc,
        tags: ['jump', 'mobility'],
    },
    'berserkers_rage': {
        id: 'berserkers_rage',
        name: "Berserker's Rage",
        description: '+10% damage per missing HP. CURSE: Cannot heal above 50% max HP.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'berserkers_rage',
        abilityId: 'curse_berserkers_rage',
        iconColor: 0x9933cc,
        tags: ['attack', 'damage', 'fire'],
    },
    'echo_strike': {
        id: 'echo_strike',
        name: 'Echo Strike',
        description: 'Every attack hits twice. CURSE: Attack speed reduced 30%.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'echo_strike',
        abilityId: 'curse_echo_strike',
        effects: [{ targetStat: 'attackSpeed', value: 0.30, operation: 'ADD' }],
        iconColor: 0x9933cc,
        tags: ['attack', 'weapon'],
    },
    'graviton_core': {
        id: 'graviton_core',
        name: 'Graviton Core',
        description: 'Enemies pulled toward you. CURSE: Fall 30% faster.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'graviton_core',
        abilityId: 'curse_graviton_core',
        iconColor: 0x9933cc,
        tags: ['damage', 'defense'],
    },
    'dark_pact': {
        id: 'dark_pact',
        name: 'Dark Pact',
        description: 'Start each floor with a random buff. CURSE: Take 1 damage at each floor start.',
        type: 'CURSED',
        rarity: 'CURSED',
        curseId: 'dark_pact',
        abilityId: 'curse_dark_pact',
        iconColor: 0x9933cc,
        tags: ['ability', 'luck'],
    },

    // ==========================================
    // CO-OP ITEMS — Only available in co-op mode
    // ==========================================

    'soul_link': {
        id: 'soul_link',
        name: 'Soul Link',
        description: 'When either player takes lethal damage, split it between both',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'soul_link',
        iconColor: 0xff4488,
        tags: ['defense', 'heal'],
        coopOnly: true,
    },
    'phoenix_feather': {
        id: 'phoenix_feather',
        name: 'Phoenix Feather',
        description: 'One-time auto-revive with full HP when you die',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'phoenix_feather',
        iconColor: 0xff8800,
        tags: ['defense', 'heal', 'fire'],
        coopOnly: true,
    },
    'shared_vigor': {
        id: 'shared_vigor',
        name: 'Shared Vigor',
        description: 'Both players gain +2 max HP',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'shared_vigor',
        iconColor: 0x44ff88,
        tags: ['health', 'heal', 'defense'],
        coopOnly: true,
    },
    'battle_bond': {
        id: 'battle_bond',
        name: 'Battle Bond',
        description: 'Both players deal +15% damage when within 200px of each other',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'battle_bond',
        iconColor: 0xffaa44,
        tags: ['attack', 'damage'],
        coopOnly: true,
    },
    'rescue_rush': {
        id: 'rescue_rush',
        name: 'Rescue Rush',
        description: 'Co-op revive timer reduced to 2 seconds',
        type: 'GOLD',
        rarity: 'LEGENDARY',
        abilityId: 'rescue_rush',
        iconColor: 0x44ddff,
        tags: ['defense', 'speed'],
        coopOnly: true,
    },
};
